language: ruby
rvm:
  - 1.9.3

gemfile: Gemfile

bundler_args: --path=vendor/bundle

before_script:
  - sh -c "psql -c 'create database ffcrm_meta_search_test;' -U postgres"
  - "export DISPLAY=:99"
  - "sh -e /etc/init.d/xvfb start"

# Run specs, acceptance tests, and ensure that assets can compile without errors
script: "bundle exec rake spec"

# To stop Travis from running tests for a new commit,
# add the following to your commit message: [ci skip]
# You should add this when you edit documentation or comments, etc.
